# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  enabled: true
  auto_review:
    enabled: true
    base_branches: ["*"]
    ignore_title_patterns: []
    ignore_labels: []

  path_filters:
    - "**/*"
  exclude_path_filters:
    - "**/*.md"
    - "**/*.txt"
    - "package-lock.json"
    - "yarn.lock"
    - "pnpm-lock.yaml"

  review_status: true
  auto_review_threshold: 0
  max_files_to_review: 100

  comment_style: "multiline"
  request_changes_workflow: false
  notifications:
    slack: false
